[cmake]
version = "3.16"
cmkr-include = "cmake/cmkr.cmake;"

[variables]
CMAKE_MODULE_PATH = "${CMAKE_CURRENT_SOURCE_DIR}/cmake"

[project]
name = "icedpp"

[find-package.Iced-Wrapper]

[target.icedpp]
type = "interface"
link-libraries = ["Iced_Wrapper"]

[target.icedpptest]
type = "executable" # executable, library, shared (DLL), static, interface, object, custom
sources = ["test.cpp"]
link-libraries = ["icedpp"]